In [2]:
# np.arange(start, stop(필수), step) : 특정 범위의 정수 배열 생성
import numpy as np
a1 = np.arange(3) # [0, 3)
a2 = np.arange(3, 9) # [3, 9)
a3 = np.arange(3, 9, 2)
print(a1)
print(a2)
print(a3)

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [14]:
# np.random.seed(num) : 똑같은 난수 배열 생성을 위한 시드 값
# np.random.randint(high, size) : 정수로 구성된 난수 배열 생성
# np.random.seed(0) # 있으면 계속해서 같은 값이 나옴
arr1 = np.random.randint(10, size = 6)
print(arr1)
arr2 = np.random.randint(10, size = (3,4))
print(arr2)
arr3 = np.random.randint(10, size = (3, 4, 5))
print(arr3)

[5 8 9 5 0 0]
[[1 7 6 9]
 [2 4 5 2]
 [4 2 4 7]]
[[[7 9 1 7 0]
  [6 9 9 7 6]
  [9 1 0 1 8]
  [8 3 9 8 7]]

 [[3 6 5 1 9]
  [3 4 8 1 4]
  [0 3 9 2 0]
  [4 9 2 7 7]]

 [[9 8 6 9 3]
  [7 7 4 5 9]
  [3 6 8 0 2]
  [7 7 9 7 3]]]


In [19]:
# arr.ndim : 차원 개수
# arr.shape : 배열 차원 크기
# arr.size : 전체 배열 크기
# arr.dtype : 배열 데이터 타입
# arr.itemsize : 배열 원소 별 메모리 크기
# arr.nbytes : 전체 배열 메모리 크기
print(arr2)

print("arr2.ndim = ", arr2.ndim)
print("arr2.shape = ", arr2.shape) # 자주 사용
print("arr2.size = ", arr2.size) # 자주 사용

print("arr2.dtype = ", arr2.dtype) # 자주 사용
print("arr2.itemsize = ", arr2.itemsize)
print("arr2.nbytes = ", arr2.nbytes)

[[1 7 6 9]
 [2 4 5 2]
 [4 2 4 7]]
arr2.ndim =  2
arr2.shape =  (3, 4)
arr2.size =  12
arr2.dtype =  int32
arr2.itemsize =  4
arr2.nbytes =  48


In [27]:
# 배열 슬라이싱 
# arr[start:stop:step]
arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[::3])
print(arr[2:8:2])

# 다차원 배열 슬라이싱
# arr[start1:stop1:step1, start2:stop2:step2]
np.random.seed(0)
arr = np.random.randint(10,size = (6, 8))
print(arr,"\n")
print(arr[3:5, 4:7])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[0 3 6 9]
[2 4 6]
[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]] 

[[5 0 2]
 [3 7 0]]
[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]]
[[99  8]
 [ 0  0]]


In [29]:
# 슬라이싱은 복사본이 아닌 뷰(view)이다.
np.random.seed(1)
arr = np.random.randint(10, size = (3, 4))
print(arr, '\n')

arr_sub = arr[:2, :2]
print(arr_sub, '\n')

arr[0,0] = 99
print(arr_sub)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[99  8]
 [ 0  0]]


In [34]:
# arr.copy() : 배열 복사본 생성
arr = np.random.randint(10, size = (2,4))
print(arr, '\n')

arr_copy = arr[:2, :2].copy()
print(arr_copy, '\n')

arr[0, 0] = 99
print(arr, '\n')
print(arr_copy)

[[8 7 3 6]
 [5 1 9 3]] 

[[8 7]
 [5 1]] 

[[99  7  3  6]
 [ 5  1  9  3]] 

[[8 7]
 [5 1]]


In [44]:
# arr.reshape() : 배열의 형상 변경 메서드
# 변경 전/후의 배열 크기가 동일해야 함
arr = np.arange(1, 10)
print(arr)
arr.reshape(3,3)
print(arr)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [37]:
# np.newaxis : 차원을 추가함
arr = np.arange(3)
print(arr, '\n')
arr_new = arr[np.newaxis, :]
print(arr_new, '\n')
arr_new = arr[:, np.newaxis]
print(arr_new, '\n')

[0 1 2] 

[[0 1 2]] 

[[0]
 [1]
 [2]] 



In [52]:
# np.concatenate() : 붙이기
# np.vstack() : 종 방향으로 배열 연결
# np.hstack() : 횡 방향으로 배열 연결
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7, 8, 9])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total, '\n')

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total, '\n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [56]:
# np.split() : 배열 분할 메서드
# np.vsplit() 
# np.hsplit()
arr = np.array([1, 2, 3, 99, 99, 3, 2, 1])
print(arr)

arr_1, arr_2, arr_3 = np.split(arr, [3,5])
print(arr_1, arr_2, arr_3)

[ 1  2  3 99 99  3  2  1]
[1 2 3] [99 99] [3 2 1]
