In [2]:
# numpy 다차원 배열 (수치연산에 특화된 라이브러리)
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
# Creating new numpy
lst = [1, 2, 3, 4]
arr = np.array(lst)
print(arr)
arr2 = np.array([5, 6, 7, 8])
print(arr2)

[1 2 3 4]
[5 6 7 8]


In [4]:
# Size Comparison for ndarray and list objects
from sys import getsizeof

# 최소 크기
lst = []
print(getsizeof(lst))
arr = np.array(lst)
print(getsizeof(arr))

# 변수가 많이 생길수록 list의 크기가 커짐
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print(getsizeof(lst))
arr = np.array(lst)
print(getsizeof(arr))

56
96
144
140


In [5]:
# Operations with NumPy Arrays
prices = [20, 25, 40, 20, 20, 35, 50, 35]

# With a List
new_prices = [price - 5 for price in prices]
print(new_prices)

# With a ndarray
prices_arr = np.array(prices)
prices_arr = prices_arr -5
print(prices_arr)

[15, 20, 35, 15, 15, 30, 45, 30]
[15 20 35 15 15 30 45 30]


In [6]:
# 실습 1
name = ['Tanya', 'Manual', 'Adwoa', 'Jeremy', 'Cody']
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)

student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores)

print(student_scores[2, 0])

print(student_scores[:, -1])

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
89
[87 91 94]


In [7]:
# Logical Operations with Arrays

# masking
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

#select using Logical operations
selected = a[a > 5]
print(selected)

#combined Logical operations / &
selected = a[(a > 6) | (a < 4)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]


In [13]:
# 실습 2
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge < 60]
print(cold)

hot = porridge[porridge > 80]
print(hot)

just_right = porridge[(porridge >= 60) & (porridge <= 80)]
print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]
