In [3]:
# Universal Functions : 대부분 더 효율적
# 백터화 연산 함수 (numpy.ufunc)

import numpy as np

def compute_reciprocals(values) :
    output = np.empty(len(values))
    for i in range(len(values)) :
        output[i] = 1.0 / values[i]
    return output

In [4]:
# Comparison : Loop vs ufuncs(vectorized)

big_array = np.random.randint(1, 100, size = 1000000)

# Looping on a big array

# jupyter magic function : 평균시간 계산
%timeit compute_reciprocals(big_array)

3.05 s ± 889 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
# Vectorized operations
%timeit 1 / big_array

3.91 ms ± 398 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
# numpy.ufunc

np.random.seed(1)
arr1 = np.random.randint(10, size = 5)
arr2 = np.random.randint(10, size = 5)
print(arr1, arr2)

arr1 = arr1 - 2
print(arr1, arr2)

arr3 = arr1 - arr2
print(arr3)

arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[  3   5   0  -3 -11]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [10]:
# UFuncs : Absolute Value
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [20]:
# np.linspace(start, stop, num) : 선형 간격의 벡터 생성
x = np.linspace(0, 100, 5) # num만큼의 간격 개수로 나옴
print(x)

# 삼각함수 : np.sin(), np.cos(), np.tan()
# 역삼각함수 : np.arcsin(), np.arccos(), np.arctan()
theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[  0.  25.  50.  75. 100.]
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [27]:
# reduce() : 배열을 특정연산으로 축소
x = np.arange(1, 5)
print(x)
aggr = np.add.reduce(x)
print(aggr)
aggr = np.multiply.reduce(x)
print(aggr)

# accumulate() : 계산의 중간 결과들을 배열로 저장
x = np.arange(1, 5)
print(x)
accum = np.add.accumulate(x)
print(accum)
accum = np.multiply.accumulate(x)
print(accum)

# sum() : 원소들의 합 (기본 sum()보다 훨씬 빠름)
np.random.seed(3)
arr = np.random.rand(1000000) # rand() : create 0 ~ 1 real numbers
print('sum = ', np.sum(arr))

[1 2 3 4]
10
24
[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]
sum =  500422.19897015305


In [37]:
# 다차원 집계, axis 속성
arr = np.arange(0, 12).reshape(3,4)
print(arr)
print(np.sum(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]
